spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5433/tech_labs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  flyway:
    enabled: true
    user: postgres
    password: postgres
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cat
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
jwt:
  secret-key: 6dO/y0CAtXmoB+KxkbMQrkDw9pogoZwN5FpRkovG50rXLRvF0ER96KNaBG/Rq8MR
